sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

matrix:
    include:
        - python: 2.7
          env: TOXENV=py27 VERSION=2.7.13
        - python: 3.3
          env: TOXENV=py33 VERSION=3.3.6
        - python: 3.6
          env: TOXENV=py36 VERSION=3.6.0
        - python: 2.7
          env: TOXENV=docs VERSION=2.7.13
          addons:
              apt:
                  packages:
                      - libenchant-dev
        - python: 2.7
          env: TOXENV=pep8 VERSION=2.7.13
        - python: 3.6
          env: TOXENV=py3pep8 VERSION=3.6.0

install:
    - ./.travis/install.sh

script:
    - ./.travis/run.sh

after_success:
    - ./.travis/upload_coverage.sh
